spring.application.name=kakak-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/kakak
spring.datasource.username=postgres
spring.datasource.password=IAMVENU123
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBnZW5lcmF0aW9u
app.jwt.expiration-ms=9000000
app.jwt.refresh-expiration-ms=604800000
