spring.application.name=kakak_backend_
spring.datasource.url=jdbc:postgresql://localhost:5432/kakak
spring.datasource.username=postgres
spring.datasource.password=IAMVENU123
spring.jpa.hibernate.ddl-auto=update

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.default-schema=kakak
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.drop-first=false
app.jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBnZW5lcmF0aW9u
app.jwt.expiration-ms=9000000
app.jwt.refresh-expiration-ms=604800000

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
logging.level.org.springframework.data.redis=DEBUG

# Error Response Details
server.error.include-message=always
server.error.include-exception=true

# Jackson Configuration
spring.jackson.deserialization.fail-on-null-for-primitives=false 