spring.application.name=kakak_backend_
spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.username=postgres
spring.datasource.password=enter a password
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBnZW5lcmF0aW9u
app.jwt.expiration-ms=9000000
app.jwt.refresh-expiration-ms=604800000

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
logging.level.org.springframework.data.redis=DEBUG
app.file-storage.directory=uploads
